config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'session/new'
    resources :sessions do
      collection do 
        post :forget_password
        post :update_password 
      end
    end
  end
  namespace :web do
    get 'users/index'
    post 'cart_items/:id/add' => 'cart_items#add_quantity', as: 'cart_item_add'
    post 'cart_items/:id/reduce' => 'cart_items#reduce_quantity', as: 'cart_item_reduce'
    delete 'cart_items/:id' => 'cart_items#destroy'
    post 'cart_items' => 'cart_items#create'
    get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
    get 'carts/:id' => 'carts#show', as: 'cart'
    delete 'carts/:id' => 'carts#destroy'
    resources :orders
    resources :users do
      collection do
        get :check_email
        get :check_email_login
      end
      member do
        get :product_details
        get :product_category
      end
    end
    resources :sessions do
      collection do
       post :forget_password
     end
   end
  end


  get '/admin' => 'admin/session#new'
  root 'web/users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_secure_password
  
  has_many :orders, dependent: :destroy
  has_many :shipping_addresse, dependent: :destroy

  after_create :assign_default_role
  validate :must_have_a_role, on: :update
 

  private

  def assign_default_role
    add_role(:user) if roles.blank?
  end

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "must have at least 1 role")
    end
  end

end

app/controllers/web/users_controller.rb
class Web::UsersController < ApplicationController
  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  
  def new
   @user = User.new
   @category = Category.all

  end    

  def create
    	 user = User.new(user_params)
          if user.save
            cookies.signed[:user_id] = user.id
            redirect_to  web_users_path, notice: "User created successfully"
         else 
          flash[:error] = "Email already exist."
          redirect_to new_web_user_path
      end
  end

  def index
     add_before_signin(session[:forwarding_url].split('/')[-1].split('=')[-1].to_i) if session[:forwarding_url].present?
    if params[:search].present?
      @products = Product.search(params[:search])
       @products = @products.paginate(page: params[:page]).order('created_at DESC')
    else
      @category = Category.all
    @products = Product.paginate(page: params[:page]).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
    end
  end

  def product_details
    @a = Product.find_by(id: params[:id])&.sub_category_id
    @sub_categories = SubCategory.find_by(id: @a)
    @products_details = @sub_categories&.products&.last(4)
    @product = Product.find_by(id: params[:id])
    @all_sub_category = @product&.category&.sub_categories
  end

  def product_category
    @products = Product.find_by(sub_category_id: params[:id])
    @sub_category = SubCategory.find_by(id: params[:id])
    @all_sub_category = @sub_category&.category&.sub_categories
    @products = @sub_category.products
  end

  def check_email
    @user = User.pluck(:email)
      if @user.include?(params[:user][:email])
        render json: false
      else
        render json: true
      end
  end

  def check_email_login
    @user = User.pluck(:email)
    if @user.include?(params[:user][:email])
      render json: true
    else
      render json: false
    end
  end

 
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:phone_no, :address)
  end

  def add_before_signin(id)
    chosen_product = Product.find(id)
    if @current_cart.products.include?(chosen_product)
       @cart_item = @current_cart.cart_items.find_by(product_id: chosen_product)
       @cart_item.quantity += 1
     else
      @current_cart.update(user_id: current_user.id) if @current_cart.user_id.blank?
      @cart_item = CartItem.new
      @cart_item.cart = @current_cart
      @cart_item.product = chosen_product
      @cart_item.quantity = 1
      @cart_item.save!
      session.delete(:forwarding_url)
    end
  end
  
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/views/web/users/_products.html.erb
 <div class="post-item">
                            <div class="row no-gutters align-items-stretch">
                                <%#binding.pry%>
                                <div class="col-md-4">
                                    <div class="post-img">
                                        <a href="/web/users/<%=product.id%>/product_details"><img src="<%= product&.image&.take&.file_url%>" alt=""></a>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="post-details">
                                        <p class="tag"><span>
                                                <%= product&.category_name%> : </span>
                                        </p>
                                        <h4 class="post-title">
                                            <a href="/web/users/<%=product.id%>/product_details"><%= product&.product_name%></a> :
                                        </h4>
                                        <p>
                                            <%= truncate(strip_tags(product&.description), omision: "...", length: 50).html_safe%>
                                        </p>
                                        <p>RS.<%= product&.price%></p>
                                       
                                        <%if !@current_cart.products.include?(product)%>
      <!-- Add to Basket -->
      <%=button_to web_cart_items_path(:product_id => product.id), class: "btn btn-warning" , style: "margin-top:15px;" , params:{productID: product.id} do %>
      <i class="fa fa-plus" style="color:black;"></i>
      Add to Basket
    <% end %>
    <%else %>

      <span>
      <%=link_to web_cart_item_reduce_path(:id =>@current_cart.cart_items.find_by(product_id: product.id)) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
      <i class="fa fa-minus" style="color:black;"></i>
      Reduce
    <% end %>

    <!-- add -->
    <%=link_to web_cart_item_add_path(:id => @current_cart.cart_items.find_by(product_id: product.id)) , method: :post , class: "btn btn-info" , style: "margin-top:15px;" do %>
    <i class="fa fa-plus" style="color:black;"></i>
    Add
  <% end %>

  <!-- Remove -->
  <%=link_to web_cart_item_path(@current_cart.cart_items.find_by(product_id: product.id)) ,method: :delete ,class: "btn btn-warning" , style: "margin-top:15px;" do %>
  <i class="fa fa-remove" style="color:black;"></i>
  Remove Item
<% end %>
</span>
<li>
  Quantity:
  <%= @current_cart.cart_items.find_by(product_id: product.id).quantity %>
  | Total Price:
  ₹ <%= @current_cart.cart_items.find_by(product_id: product.id).total_price %>
</li>
<%end %>
                                    
                                    </div>
                                </div>
                            </div>
                       
                        </div>
                        

app/views/web/users/index.html.erb
<div class="home-slider">

    <% @products.each do |trend| %>
    <a href="/web/users/<%= trend.id %>/product_details">
    <div class="slide">
        <div class="slide-img setimg cover" style="background-image: url('<%= trend&.image&.last&.file_url %>')"></div>
        <div class="slide-content container">
            <div class="slide-text" style="margin-left: 50px">
            
                <h1>
                    <%= trend.product_name%>
                </h1>
                <div class="release-name">
                    <h4>
                        <%= trend.product_name%> (
                        <%= trend.category_name%>,
                        <%= trend&.updated_at&.strftime("%Y")%> )</h4>
                    <h5>
                        <%= trend.sub_category_name%>
                    </h5>
                </div>
                <p>
                    <%= truncate(strip_tags(trend.description), omision: "...", length: 150).html_safe%>
                </p>
            </div>
        </div>
        
    </div>
    </a>
    <%end%>
</div>
<!-- Home Slider Close -->
<div class="page-wrapper">
    <div class="container home-wrap">
        <div class="row">
            <div class="col-md-8">
                <div class="left-side">
                    <h3 class="widget-title mt-0">TRENDING NOW</h3>
                    <div class="posts", id="posts">
                        <%# @count_trending = 0 %>
                        <ul>
                        <% @products&.each_with_index do |product, index|%>
                        <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>

                    <%= render 'web/users/products' , :product => product%>

                            <%end%>
                    </div>
                </div>
            </div>
           
        </div>
     

          
        
       
      
        
    </div>
</div>
  <% if @products.next_page %>
    <div id="infinite-scrolling">
      <%= will_paginate @products %>
    </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
    // debugger;
    $('#1').click();
    $('.user_type1').click(function() {
        debugger;
        var id = this.id;
        $.ajax({
            url: '/web/users',
            type: 'get',
            data: {
                id: id
            }
        });
    });
});
</script>
<script type="text/javascript">
$(document).ready(function() {
    $('#1').click();
    $('.data_category').change(function() {
        var id = this.value;
        $.ajax({
            url: '/web/users.js',
            type: 'get',
            data: {
                id: id
            }
        });
    });
});
</script>
<script type="text/javascript">
$(document).ready(function() {
    $(".ratingText").shorten({
        "showChars": 500,
        "moreText": "View More",
        "lessText": "Less",
    });
});
</script>

<script type="text/javascript">
jQuery(document).ready(function() {
    jQuery('.home-slider').slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
    });

    $('.home-slider1').slick({
        dots: true,
        infinite: true,
        autoplay: true,
        arrows: false,
        speed: 300,
        slidesToShow: 3,
        responsive: [{
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    infinite: true,
                }
            },
            {
                breakpoint: 991,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    infinite: true,
                }
            },
            {
                breakpoint: 767,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                }
            }
            // You can unslick at a given breakpoint now by adding:
            // settings: "unslick"
            // instead of a settings object
        ]
    });
});
</script>

app/views/web/users/index.js.erb
var delimiter =
        $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#posts').append(delimiter);
$('#posts').append('<%= j render @products %>');
$('.pagination').replaceWith('<%= j will_paginate @products %>');
preparePagination(delimiter);
<% unless @products.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/web/users/new.html.erb
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
 <div class="page-wrapper">
      <div class="login-page">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-lg-10 col-xl-8 offset-xl-2 offset-lg-2">
              <div class="login-box">
                <div class="row no-gutters row-eq-height">
                  <div class="col-md-5 col-xl-5">
                    <div class="login-content-box">
                      <div class="login-text">
                        <h3>Welcome</h3>
                        <h2>to website</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                          laboris nisi ut aliquip ex ea commodo consequat.</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-7 col-xl-7">
                    <div class="login-form-box">
                      <div class="right-heading">
                        <h2>Join Us</h2>
                      </div>
                      <%#= form_for(resource, as: resource_name, url: registration_path(resource_name),:html => {:id => "registration_form"}) do |f| %>
                     <%= form_for @user, url: web_users_path, html: {id: "registration_form"} do |f| %>
                      
                      <%#= render "devise/shared/error_messages", resource: resource %>
                        <div class="form-group">
                          <br>
                          <!-- <input type="text" class="form-control" id="" placeholder="Username"> -->
                           <%= f.text_field :name, autofocus: true, class: "form-control", id: "user_name", placeholder: "Username" %>
                           <span class="msg-error1 error"></span>
                        </div>
                        <div class="form-group">
                          <br>
                           <%= f.select :roles, Role.all.collect {|p| [p.name] }, {:include_blank => "Select Role" },{:class => "form-control", :required => true} %>
                           <span class="msg-error1 error"></span>
                        </div>
                        <div class="form-group">
                          <!-- <input type="email" class="form-control" id="" placeholder="Email Address"> -->
                          <%= f.email_field :email, autocomplete: "email", class: "form-control", id: "user_email", placeholder: "Email Address" %>
                          <span class="msg-error2 error"></span>
                        </div>
                        <div class="form-group">
                          <!-- <input type="Password" class="form-control" id="" placeholder="Password"> -->
                         <%= f.password_field :password, autocomplete: "new-password", class: "form-control", id: "user_pass", placeholder: "Password" %>
                           <span class="msg-error3 error"></span>

                        </div>
                        <div class="form-group">
                          <!-- <input type="Password" class="form-control" id="" placeholder="Confirm Password"> -->
                          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control",id: "user_conf_pass", placeholder: "Confirm Password" %>
                          <span class="msg-error4 error"></span>

                        </div>
                        <div class="form-group text-center mb-0">
                           <%= f.submit "REGISTER", class: "btn btn-block btn-theme" %>
                          <!-- <a href="#" class="btn btn-success">Register</a> -->
                        </div>
 
                        <p class="text-center mt20"> Already a member? <a class="yellow-text"><%= link_to "Login", new_web_session_path, :class => 'nav-link btn btn-theme'  %></a></p>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


<style type="text/css">
  .msg-error{
        color: #e80b0b;
  }
  .error{
            color: #e80b0b;
  }
</style>

app/views/web/users/product_category.html.erb
<style type="text/css">
    .activea{
        background: #D6D6D1!important;
    }
</style>

<%arr = @sub_category.products.map { |p| p&.image&.first&.file&.url}%>
<%arr = arr[0..3]%>
<div class="container">
    <div class="row navtop">
        <ul class="nav1">
            <%@all_sub_category.each do |sub|%>
            <li class="nav2"><a class='<%= params[:id] == sub.id ? "activea" : "" %>' href="/web/users/<%=sub.id%>/movie_category">
                    <%=sub&.sub_category_name%></a></li>
            <%end%>
        </ul>
    </div>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <%arr.each_with_index do |img,index|%>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class='<%= index == 0 ? "active" : "" %>'></li>
        <%end%>
    </ol>
    <div class="carousel-inner">
        <%arr.each_with_index do |img,index|%>
        <div class='carousel-item <%= index == 0 ? "active" : "" %>'>
            <img class="d-block w-100" src="<%=img%>" alt="First slide" height="500px;">
        </div>
        <%end%>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    </a>
</div>
<div class="page-wrapper">
    <div class="container home-wrap">
        <h2 class="widget-title mt-0">
            <%= @sub_category&.sub_category_name%>
        </h2>
        <div class="row theatres-row">
            
            <div class="custom-slider slidw">
                <% @products_movie_category&.each do |product_name|%>

               
                 <a href="/web/users/<%=product_name.id%>/movie_detail" class="custom-post custom-slide">
                    <div class="custom-img">
                        <%#= current_user&.image&.file&.present? ? current_user&.image&.file.try(:url) : "/assets/user_no_image.png" %>
                        <img src='<%= product_name&.image&.first&.file&.present? ? product_name&.image&.first&.file.try(:url) : "/assets/tv58.png" %>' class="img-fluid" alt="">
                        <%#binding.pry%>
                    </div>
                    <div class="custom-content justify-content-end">
                        <h4 class="custom-title">
                            <%= product_name&.product_name%>
                        </h4>
                        <p class="mb-2">
                            <%= truncate(strip_tags(product_name&.description), omision: "...", length: 130).html_safe%>
                        </p>
                        <!-- <a href="#" class="view-more align-self-end">View More</a> -->
                    </div>
             
                </a>
               
                <%end%>
            </div>
        </div>
    </div>
</div>
<script src="/assets/web/custom.js"></script>
<script>
    $('.custom-slider').slick({
      dots: false,
      infinite: true,
      autoplay: true,
      speed: 300,
      slidesToShow: 3,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 1,
            infinite: true,
          }
        },
        {
          breakpoint: 991,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 1,
            infinite: true,
          }
        },
        {
          breakpoint: 767,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
          }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
      ]
    });

  </script>
<style type="text/css">
p.paramusic {
    margin-bottom: -40px;
}
</style>
<script>
$(document).ready(function(){
  $('[data-toggle="popover"]').popover();   
});
</script>

app/views/web/users/product_details.html.erb
<style type="text/css">
    .activea{
        background: #D6D6D1!important;
    }
</style>
<%arr = @product.image { |i| i&.file&.url}%>
<%arr = arr[0..3]%>
<div class="container">
    <div class="row navtop">
        <ul class="nav1">
            <%@all_sub_category.each do |sub|%>
            <li class="nav2"><a class='<%= @product.sub_category.id == sub.id ? "activea" : "" %>' href="/web/users/<%=sub.id%>/movie_category">
                    <%=sub&.sub_category_name%></a></li>
            <%end%>
        </ul>
    </div>
</div>


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <%arr.each_with_index do |img,index|%>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class='<%= index == 0 ? "active" : "" %>'></li>
        <%end%>
         </ol>
    <div class="carousel-inner">
        <%arr.each_with_index do |img,index|%>
        <div class='carousel-item <%= index == 0 ? "active" : "" %>'>
            <img class="d-block w-100" src="<%=img&.file&.url%>" alt="First slide" height="530px;">
        </div>
        <%end%>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    </a>
</div>
<div class="page-wrapper page-Nav2">
    <%#= render partial: 'web/users/trending'%>
    <div class="container home-wrap">
        <div class="row theatres-row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-6 leftsec">
                        <h4 class="topheading">
                            <%=@product&.product_name%>
                        </h4>
                    </div>
                </div>
                <div>
                    <p class="mainpara">
                        <%=ActionView::Base.full_sanitizer.sanitize(@product&.description)%>
                    </p>
                </div>
            </div>
          
        </div>
        <div class="heading">
            <h2 class="titile-light">You may also like:</h2>
        </div>
        <div class="custom-slider slidw">
            <%@products_details&.each do |product|%>
            <a href="/web/users/<%=product.id%>/movie_detail" class="custom-post custom-slide">
                <div class="custom-img">
                    <img src='<%= product&.image&.first&.file&.present? ? product&.image&.first&.file.try(:url) : "/assets/tv58.png" %>' class="img-fluid " alt="">
                </div>
                <div class="custom-content justify-content-end">
                    <h4 class="custom-title">
                        <%=product&.product_name%>
                    </h4>
                    <p class="mb-2">
                        <%= truncate(strip_tags(product&.description), omision: "...", length: 130).html_safe%>
                    </p>
                    <!-- <a href="#" class="view-more align-self-end">View More</a> -->
                </div>
            </a>
            
           
           <%end%>
        </div>
    </div>
</div>
</div>
<script>
    $('.custom-slider').slick({
    dots: false,
    infinite: true,
    autoplay: true,
    speed: 300,
    slidesToShow: 3,
    responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
        infinite: true,
      }
    },
    {
      breakpoint: 991,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        infinite: true,
      }
    },
    {
      breakpoint: 767,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      }
    }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
        ]
      });

    </script>
<style type="text/css">
.video_product {
    height: 100%;
    max-height: 359px;
    width: 100%;
    max-width: 976px;
}
</style>