config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'session/new'
    resources :sessions do
      collection do 
        post :forget_password
        post :update_password 
      end
    end
  end
  namespace :web do
    get 'users/index'
    post 'cart_items/:id/add' => 'cart_items#add_quantity', as: 'cart_item_add'
    post 'cart_items/:id/reduce' => 'cart_items#reduce_quantity', as: 'cart_item_reduce'
    delete 'cart_items/:id' => 'cart_items#destroy'
    post 'cart_items' => 'cart_items#create'
    get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
    get 'carts/:id' => 'carts#show', as: 'cart'
    delete 'carts/:id' => 'carts#destroy'
    resources :orders
    resources :users do
      collection do
        get :check_email
        get :check_email_login
      end
      member do
        get :product_details
        get :product_category
      end
    end
    resources :sessions do
      collection do
       post :forget_password
     end
   end
  end


  get '/admin' => 'admin/session#new'
  root 'web/users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_detail.rb
class BankDetail < ApplicationRecord
    
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
  has_many :products, through: :cart_items

  def sub_total
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.total_price
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
  belongs_to :cart

  def total_price
    if valid_quantity_and_price?
      quantity.to_s.to_i * product.price.to_s.to_i
    else
      0.0
    end
  end

  def valid_quantity_and_price?
    !quantity.to_s.strip.empty? && !product.price.to_s.strip.empty?
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :sub_categories, autosave: true, dependent: :destroy
  has_many :product, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :file, ImageUploader
    belongs_to :imageable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    belongs_to :user
    has_one :shipping_address, dependent: :destroy
  
    def sub_total
      sum = 0
      cart_items.each do |cart_item|
        sum += cart_item.total_price
      end
      sum
    end
  
    def self.make_payment(token, total_price)
      Rails.logger.debug "-----------token------#{token.inspect}---"
      Rails.logger.debug "-----------price------#{total_price.inspect}---"
      begin
        Rails.logger.debug '-----begin--------'
        response = Stripe::Charge.create(
          amount: total_price,
          currency: 'inr',
          description: 'Example Charge',
          capture: false,
          source: token
        )
        response.capture
        Rails.logger.debug "-------response--------#{response.inspect}------------"
        [true, response]
      rescue StandardError => e
        [false, e.message]
      end
    end
  
    def self.update_address(name, number, pin_code, address, user_id, order_id)
      order = ShippingAddress.new(name: name, number: number, pin_code: pin_code, address: address, user_id: user_id,
                                  order_id: order_id)
      order.save!
    end
  
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :sub_category
  belongs_to :category
  has_many :image, class_name: 'Image', as: :imageable, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :image, allow_destroy: true
  has_many :cart_items, dependent: :destroy
  has_many :orders, through: :cart_items
  self.per_page = 10

  def self.search(search)
    where(['product_name ILIKE ? OR category_name ILIKE ? OR sub_category_name ILIKE ?', "%#{search}%", "%#{search}%",
           "%#{search}%"])
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :order
  belongs_to :user
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
  has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_secure_password
  
  has_many :orders, dependent: :destroy
  has_many :shipping_addresse, dependent: :destroy

  after_create :assign_default_role
  validate :must_have_a_role, on: :update
 

  private

  def assign_default_role
    add_role(:user) if roles.blank?
  end

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "must have at least 1 role")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_cart
  include ApplicationHelper
  helper_method :current_user


  def current_user
    current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  end

  private

  def set_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      cart.present? ? (@current_cart = cart) : (session[:cart_id] = nil)
    end
    return unless session[:cart_id].nil?

    @current_cart = Cart.create!(user_id: nil)
    session[:cart_id] = @current_cart.id
  end

  def logged_in_user
    return if current_user.present?

    store_location
    flash[:danger] = 'please login in.'
    redirect_to new_web_session_path
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper

    def current_user
        # binding.pry
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def log_in(user)
        session[:user_id] = user.id
      end
    
     
      # Returns true if the user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end
    
      # Forgets a persistent session.
      def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
      end
    
      # Logs out the current user.
      def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
      end
    
      # Redirects to stored location (or to the default).
      def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
      end
    
      # Stores the URL trying to be accessed.
      def store_location
        session[:forwarding_url] = request.original_url #if request.get?
      end
end

app/helpers/web/carts_helper.rb
module Web::CartsHelper
end

app/helpers/web/orders_helper.rb
module Web::OrdersHelper
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/views/layouts/_adminlte_control_sidebar.html.erb
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>

app/views/layouts/_adminlte_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

app/views/layouts/_adminlte_header.html.erb
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>CS</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>ACS</b>Solutions</span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <!-- /.messages-menu -->
                <!-- Notifications Menu -->
                <!-- Tasks Menu -->
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <p>
                                <small></small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <!-- <a class="btn btn-default btn-flat" href="<%#=destroy_user_session_path%>">Log Out</a>  -->
                                <!-- <a href="/users/sign_out" class="btn btn-default btn-flat">Sign out</a> -->
                                <%#= link_to "Sign out", destroy_user_session_path, :class=> "btn btn-default btn-flat"  %>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/_adminlte_sidebar.html.erb
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/assets/circle.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
        <p>Welcome <%= current_user&.name %></p>

          <!-- Status -->
          <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
        </div>
      </div>

      

      <!-- Sidebar Menu -->
       <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <!-- <li class="header">HEADER</li> -->
        <!-- Optionally, you can add icons to the links -->
      <li id="index"><a href="/admin/home/index"><i class='fa fa-link'></i> <span>Dashboard</span></a></li>
      <li id="categories"><a href="/admin/categories"><i class="fa fa-link"></i> <span>Category Management</span></a></li>
      <li id="products"><a href="/admin/products"><i class="fa fa-link"></i> <span>Products Management</span></a></li>
      <li id="users"><a href="/admin/users"><i class="fa fa-users"></i> <span>User Management</span></a></li>
      

    </ul>
    <!-- /.sidebar-menu -->
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>


  <script type="text/javascript">
 // on click change active class js on home page.
$(function() {
 // debugger;
pathname = window.location.pathname;
url_array = location.pathname.split("/");
if (url_array.length <= 2)
 { 
 element = $("#"+url_array[1])[0];
 element.classList.add("active");
 }
 else if(url_array.length == 3)
 {
 element = $("#"+url_array[2])[0];
   element.classList.add("active");
 }
else if(url_array.length==4)
 {
   if (url_array[3]=="feedback" || url_array[3] == "index")
   {
     element = $("#"+url_array[3])[0];
    element.classList.add("active");
   }
   else
   {
   element = $("#"+url_array[2])[0];
   element.classList.add("active");
   }
 }
 else if(url_array.length == 5 && url_array[4]=="edit")
 {
  element = $("#"+url_array[2])[0];
  element.classList.add("active");
 }

else if(url_array.length<=4 && url_array[2] == "faqs")
 {
 element = $("#"+url_array[2])[0];
   element.classList.add("active");
 }
 
else
 {
    element = $("#"+url_array[4])[0];
    element.classList.add("active");
 }
});
// on click change active class js end on home page.
</script>
<style type="text/css">
 .skin-blue .sidebar-menu>li:hover>a, .skin-blue .sidebar-menu>li.active>a {
   color: #fff;
   background: #f39c12;
   border-left-color: #3c8dbc;
}
</style>

app/views/layouts/_web_footer.html.erb
<footer class="footer">
    <div class="container">
    
    </div>
    <div class="last-para copyright text-center">
        <div class="container">
            <p class="mb-0">© 2021 www.ecommerce.com. All rights reserved.</p>
        </div>
    </div>
</footer>

app/views/layouts/_web_header.html.erb
<header id="header" class="header">
    <nav id="main-navbar" class="main-navbar navbar navbar-expand-lg bg-primary">
        <div class="headerTop">
            <a class="navbar-brand" href="<%= root_path%>"><img src="/assets/LOGO.png"></a>
            <ul class="navbar-nav align-items-center">
                <li class="nav-item">
                    <!-- <form class="header-search"> -->
                        <%= form_tag "/web/users", method: :get, class: "header-search" do %>
                         <input type="search" name="search" class="form-control" placeholder="Search">
                         <img src="/assets/search.png">
                    <!-- </form> -->
                        <%end%>
                </li>
            </ul>
            <ul class="navbar-nav align-items-center">
                <%if current_user%>
                <li class="nav-item user-item">
                    <a class="" href="/web/users/<%= current_user.id %>/user_profile">
                        <span>
                         <%= current_user&.name%>
                       </span> 
                </a>
            </li>
                <div class="nav-link btn btn-theme" >
                <li><%= link_to 'Logout', web_session_path(current_user.id), method: :delete, class: "" %></li>
                </div>

                </li>
                <!-- Cart -->
      <li><%= link_to web_cart_path(@current_cart) do %>
        My Cart
        <span class="badge ">
          <i class="fa fa-cart-plus" style="color:#FFD700; font-size:20px"></i>

          <i id="total_cart_items_badge">(<%= @current_cart.cart_items.count %>)</i>
        </span>
      <% end %>
    </li>

    <!-- Orders -->
    <li><%= link_to web_orders_path do %>
      My Orders
      <span class="badge ">
          <i class="fa fa-shopping-basket" style="color:#FFD700; font-size:20px"></i>
          (<%= current_user.orders.count %>)

      </span>
    <% end %>
  </li>
                <%else%>
                <li>
                    <%= link_to "+ Join Us", new_web_user_path, :class => 'nav-link btn btn-theme mr-3'  %>
                </li>
                <li>
                    <%= link_to "Login", new_web_session_path, :class => 'nav-link btn btn-theme'  %>
                </li>
                <%end%>
            </ul>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <%#binding.pry%>
        <%if request.url == "http://localhost:3000/web/orders"%>
        <div>
            
        </div>
        <%else%>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center main-nav">
                <%if @product.present?%>
                <%xyz = @product&.category&.id%>
                <%else%>
                <%xyz = @sub_category&.category&.id%>
                <%end%>
                <% @category.each do |category|%>
                <li class="nav-item dropdown mega-dropdown">
                    <a class="nav-link user_type dropdown-toggle shubham <%= xyz == category.id ? "active" : "" %>"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="javascript:void(0);" id="<%= category.id%>">
                        <%= category.category_name%></a>
                    <div class="dropdown-menu mega-menu">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="custom-post m-0">
                                    <div class="custom-img">
                                        <% arr = category.sub_categories.map{ |s_c| s_c.products.map { |p| p&.image&.first&.file&.url}}.flatten.compact%>
                                        <%if arr.present? %>
                                        <img src="<%=arr[0]%>" class="img-fluid" alt="">
                                        <%else%>
                                        <img src="/assets/mega-drop-img.jpg" class="img-fluid" alt="">
                                        <%end%>
                                    </div>
                                    <div class="custom-content justify-content-end">
                                        <p class="mb-2">
                                            <%= category.category_name%>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    <% category&.sub_categories.each_with_index do |sub, index| %>
                                    <% if index <= 2 && index %>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li>
                                                <a class="" role="button" href="/web/users/<%=sub.id%>/product_category">
                                                    <%= sub&.sub_category_name%></a>
                                            </li>
                                           
                                        </ul>
                                    </div>
                                    <!-- </div> -->
                                    <% elsif index <= 5%>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li><a href="/web/users/<%=sub.id%>/product_category">
                                                    <%= sub&.sub_category_name%></a></li>
                                        </ul>
                                    </div>
                                    <%elsif index <= 19%>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li><a href="/web/users/<%=sub.id%>/product_category">
                                                    <%= sub&.sub_category_name%></a></li>
                                        </ul>
                                    </div>
                                    <%end%>
                                    <% end %>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
             
            </ul>
        </div>
        <%end%>
    </nav>
</header>

<script type="text/javascript">
// $(document).ready(function() {
//     $('#header .navbar-nav > li > a').click(function() {
//         $('li a').removeClass("active");
//         $(this).addClass("active");
//     });
//     $('#header .mega-menu-list > li > a').click(function() {
//         $('li a').removeClass("active");
//         $(this).addClass("active");
//     });
// });
// $("#header ul li a").each(function() {
//     if ((window.location.pathname.indexOf($(this).attr('href'))) > -1) {
//         $(this).addClass('activeMenuItem');
//     }
// });
</script>
<style type="text/css">
    .shubham:hover{
        color: #fe7100;
        font-weight: bold;
    }
</style>

app/views/layouts/adminlte.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ACS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render "layouts/adminlte_header"%>
    <%= render "layouts/adminlte_sidebar"%>
    <div class="content-wrapper">
      <section class="content container-fluid">
        <%= yield %>
      </section>
    </div>
    <%= render "layouts/adminlte_footer"%>
    <%= render "layouts/adminlte_control_sidebar"%>
    <div>
</body>

</html>

app/views/layouts/application.1html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acstask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Acstask</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'web', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'web', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag :defaults, "nested_form" %>
  <%#= javascript_include_tag Ckeditor.cdn_url %>
</head>

<body>
  <%= render 'layouts/messages' %>
  <div class="wrapper">
    <%= render "layouts/web_header"%>
    <%= yield %>
    <%= render "layouts/web_footer" %>
  </div>
</body>

</html>

app/views/layouts/mailer1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mailer1.text.erb
<%= yield %>

app/views/web/shared/_cart.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Cart</h1>
  </div>
</section>

<div class="container mb-4">
  <div class="row">
    <div class="col-12">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Product</th>
              <th scope="col">Available</th>
              <th scope="col" class="text-center">Quantity</th>
              <th scope="col" class="text-right">Price</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart.cart_items.each do |cart_item| %>
              <%= render 'web/shared/cart_cart_item' , :product => cart_item.product , :cart_item => cart_item %>
            <% end %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Sub-Total</td>
              <td class="text-right">₹ <%= @cart.sub_total %></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Shipping</td>
              <td class="text-right">free</td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>
                <strong>Total</strong>
              </td>
              <td class="text-right">
                <strong>₹ <%= @cart.sub_total %></strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col mb-2">
      <div class="row">
        <div class="col-sm-12  col-md-4">
          <%= button_to "Continue Shopping", root_path , class: "btn btn-block btn-light" , method: :get%>
        </div>
        <% if(@current_cart.cart_items.count !=0 ) %>
          <div class="col-sm-12  col-md-4">
            <%= button_to "Empty cart", web_cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-lg btn-block btn-warning text-uppercase"%>
          </div>
          <div class="col-sm-12 col-md-4 text-right">
            <%= button_to "Checkout", new_web_order_path , method: :get,class: "btn btn-lg btn-block btn-info text-uppercase"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/web/shared/_cart_cart_item.html.erb
<tr>
  <td><%#= link_to product do%>
    <% if product.image.present? %>
      <%= image_tag product&.image&.take&.file_url , size:"90x90"%>
    <% else %>
      <%= image_tag "/assets/images/arrow.png", size:"90x90" %>
    <%end%>
  <%#end %>
  x
  <%= cart_item.quantity %>
</td>
<td><%= product.product_name %></td>
<td>In stock</td>
<td class="text-center">
  <!-- reduce -->
  <%=link_to web_cart_item_reduce_path(:id => cart_item) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
  <i class="fa fa-minus" style="color:white;"></i>

<% end %>
<!-- add -->
<%=link_to web_cart_item_add_path(:id => cart_item) , method: :post , class: "btn btn-info" , style: "margin-top:15px;" do %>
<i class="fa fa-plus" style="color:white;"></i>
<% end %>
</td>
<td class="text-right"><%= product.price %>
₹</td>
<td class="text-right">
<!-- Remove -->
<%=link_to web_cart_item_path(cart_item) ,method: :delete ,class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
<i class="fa fa-trash"></i>
<% end %>
</td>
</tr>